# Generated by Django 3.1.3 on 2023-09-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230918_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
        ),
    ]
